-- +goose Up
ALTER TABLE todos MODIFY COLUMN id INT NOT NULL;
ALTER TABLE todos DROP PRIMARY KEY;
ALTER TABLE todos DROP COLUMN id;
ALTER TABLE todos ADD COLUMN id UUID PRIMARY KEY NOT NULL DEFAULT (UUID());

-- +goose Down
ALTER TABLE todos DROP COLUMN id;
ALTER TABLE todos ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY;
